### ISSUE TITLE
Undefined reference spline_4_d

### ISSUE THREAD

**Issue by maxspahn** [oscardegroot/ros_tools#3]
If using ROS1 and thus using the switch_to_ros.py script, the not-found file is added back to the CMakeLists.txt.

https://github.com/oscardegroot/ros_tools/blob/a15cc154ef4657ca5b8320407224847d06f44a2b/CMakeLists1.txt#L45

**Comment by oscardegroot** [comment]
Thanks Max, it is fixed in 33c373d4905a741c16c837d1a6f4a04b5db87938
